// Public-facing read-only landing page for shared reports.
// Anyone with the link can view if the report's `is_public` flag is true.
// No auth required — RLS policy "Anyone can read public reports" enforces access.
import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { exportReportPdf } from "@/lib/reports/exporters";
import type { Report, ReportBlock } from "@/lib/reports/types";
import { Download, FileText, ExternalLink, Loader2 } from "lucide-react";
import { ChartBlockView, TableBlockView, MapBlockView } from "@/components/reports/BlockViews";
import { PdfStyleBlockView } from "@/components/reports/PdfStyleBlockView";

export default function PublicReport() {
  const { id } = useParams<{ id: string }>();
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      if (!id) return;
      const { data, error } = await supabase.from("reports").select("*").eq("id", id).maybeSingle();
      if (error || !data) { setError("Report not found or not public"); setLoading(false); return; }
      if (!(data as any).is_public) { setError("This report is not publicly shared"); setLoading(false); return; }
      setReport(data as unknown as Report);
      setLoading(false);
    })();
  }, [id]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center gap-4 bg-background p-8 text-center">
        <FileText className="h-12 w-12 text-muted-foreground" />
        <h1 className="text-xl font-bold">{error ?? "Report not available"}</h1>
        <Link to="/" className="text-sm text-primary hover:underline">← Back to ORDB</Link>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-card sticky top-0 z-10">
        <div className="max-w-5xl mx-auto px-4 py-3 flex items-center justify-between gap-2 flex-wrap">
          <div className="min-w-0">
            <Link to="/" className="text-[10px] text-muted-foreground hover:underline flex items-center gap-1">
              <ExternalLink size={10} /> ORO — Opposition Research Database
            </Link>
            <h1 className="text-lg font-bold truncate">{report.title}</h1>
          </div>
          <button
            onClick={() => exportReportPdf(report)}
            className="text-xs flex items-center gap-1 px-3 py-1.5 bg-primary text-primary-foreground rounded hover:opacity-90"
          >
            <Download size={12} /> Download PDF
          </button>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 py-6 space-y-4">
        {report.description && (
          <p className="text-sm text-muted-foreground italic border-l-2 border-primary pl-3">
            {report.description}
          </p>
        )}

        {report.blocks.length === 0 && (
          <div className="text-center py-12 text-sm text-muted-foreground italic">
            (Empty report)
          </div>
        )}

        {report.blocks.map((b) => (
          <PublicBlock key={b.id} block={b} />
        ))}

        <footer className="pt-8 mt-8 border-t border-border text-[10px] text-muted-foreground text-center">
          Last updated {new Date(report.updated_at).toLocaleString()} ·
          Generated by <Link to="/" className="hover:underline text-primary">ORO ORDB</Link>
        </footer>
      </main>
    </div>
  );
}

function PublicBlock({ block }: { block: ReportBlock }) {
  return <PdfStyleBlockView block={block} />;
}
