// Public-facing read-only landing page for shared reports.
// Anyone with the link can view if the report's `is_public` flag is true.
// No auth required — RLS policy "Anyone can read public reports" enforces access.
import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { exportReportPdf } from "@/lib/reports/exporters";
import type { Report, ReportBlock } from "@/lib/reports/types";
import { Download, FileText, ExternalLink, Loader2 } from "lucide-react";
import { ChartBlockView, TableBlockView, MapBlockView } from "@/components/reports/BlockViews";

export default function PublicReport() {
  const { id } = useParams<{ id: string }>();
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      if (!id) return;
      const { data, error } = await supabase.from("reports").select("*").eq("id", id).maybeSingle();
      if (error || !data) { setError("Report not found or not public"); setLoading(false); return; }
      if (!(data as any).is_public) { setError("This report is not publicly shared"); setLoading(false); return; }
      setReport(data as unknown as Report);
      setLoading(false);
    })();
  }, [id]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center gap-4 bg-background p-8 text-center">
        <FileText className="h-12 w-12 text-muted-foreground" />
        <h1 className="text-xl font-bold">{error ?? "Report not available"}</h1>
        <Link to="/" className="text-sm text-primary hover:underline">← Back to ORDB</Link>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-card sticky top-0 z-10">
        <div className="max-w-5xl mx-auto px-4 py-3 flex items-center justify-between gap-2 flex-wrap">
          <div className="min-w-0">
            <Link to="/" className="text-[10px] text-muted-foreground hover:underline flex items-center gap-1">
              <ExternalLink size={10} /> ORO — Opposition Research Database
            </Link>
            <h1 className="text-lg font-bold truncate">{report.title}</h1>
          </div>
          <button
            onClick={() => exportReportPdf(report)}
            className="text-xs flex items-center gap-1 px-3 py-1.5 bg-primary text-primary-foreground rounded hover:opacity-90"
          >
            <Download size={12} /> Download PDF
          </button>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 py-6 space-y-4">
        {report.description && (
          <p className="text-sm text-muted-foreground italic border-l-2 border-primary pl-3">
            {report.description}
          </p>
        )}

        {report.blocks.length === 0 && (
          <div className="text-center py-12 text-sm text-muted-foreground italic">
            (Empty report)
          </div>
        )}

        {report.blocks.map((b) => (
          <PublicBlock key={b.id} block={b} />
        ))}

        <footer className="pt-8 mt-8 border-t border-border text-[10px] text-muted-foreground text-center">
          Last updated {new Date(report.updated_at).toLocaleString()} ·
          Generated by <Link to="/" className="hover:underline text-primary">ORO ORDB</Link>
        </footer>
      </main>
    </div>
  );
}

function PublicBlock({ block }: { block: ReportBlock }) {
  switch (block.type) {
    case "heading":
      return <h2 className="text-2xl font-bold text-primary border-b border-border pb-1">{block.text}</h2>;
    case "subheading":
      return <h3 className="text-lg font-bold mt-3">{block.text}</h3>;
    case "text":
      return <p className="text-sm whitespace-pre-wrap leading-relaxed">{block.text}</p>;
    case "image":
      return (
        <figure>
          <img src={block.url} alt={block.caption ?? ""} className="max-w-full rounded border border-border" />
          {block.caption && <figcaption className="text-[10px] text-muted-foreground mt-1 italic">{block.caption}</figcaption>}
        </figure>
      );
    case "divider":
      return <hr className="border-border my-4" />;
    case "page_break":
      return <div className="border-t border-dashed border-border my-6" />;
    case "tabs":
      return (
        <div className="space-y-3">
          {block.tabs.map((t) => (
            <details key={t.id} className="border border-border rounded p-2" open>
              <summary className="text-sm font-bold cursor-pointer">{t.label}</summary>
              <div className="space-y-3 pt-2">
                {t.blocks.map((b) => <PublicBlock key={b.id} block={b} />)}
              </div>
            </details>
          ))}
        </div>
      );
    case "chart": return <ChartBlockView block={block} />;
    case "table": return <TableBlockView block={block} />;
    case "map":   return <MapBlockView block={block} />;
    default: {
      const snap = (block as any).snapshot;
      return (
        <div className="border border-border rounded p-3 bg-card">
          <div className="text-xs font-bold uppercase text-muted-foreground mb-1">
            {block.type}{block.title ? ` — ${block.title}` : ""}
          </div>
          {snap ? (
            <pre className="text-[10px] overflow-x-auto bg-muted p-2 rounded max-h-72">
              {JSON.stringify(snap, null, 2)}
            </pre>
          ) : (
            <div className="text-xs text-muted-foreground italic">(no cached data)</div>
          )}
        </div>
      );
    }
  }
}
