// Build a TS module bundling all *-Technical.md + TECHNICAL-REFERENCE.md
// for the edge function (no runtime FS needed).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const WIKI = "wiki";
const techFiles = readdirSync(WIKI).filter(f => /-Technical\.md$/.test(f) || f === "TECHNICAL-REFERENCE.md");

const entries = techFiles.map(f => {
  const slug = f.replace(/\.md$/, "");
  const content = readFileSync(`${WIKI}/${f}`, "utf8");
  const titleMatch = content.match(/^#\s+(.+)$/m);
  const title = titleMatch ? titleMatch[1].trim() : slug;
  return { slug, title, content };
});

const out = `// AUTO-GENERATED by scripts/gen-technical-bundle.ts — DO NOT EDIT BY HAND
export interface TechnicalDoc { slug: string; title: string; content: string; }
export const TECHNICAL_DOCS: TechnicalDoc[] = ${JSON.stringify(entries, null, 2)};
export const TECHNICAL_DOCS_BY_SLUG: Record<string, TechnicalDoc> =
  Object.fromEntries(TECHNICAL_DOCS.map(d => [d.slug, d]));
`;

writeFileSync("supabase/functions/_shared/technical-docs.ts", out);
console.log(`Bundled ${entries.length} technical docs into _shared/technical-docs.ts`);
